import type { AppConfig } from '../types';

/**
 * Get default configuration for repo2txt plugin
 */
export function getDefaultConfig(): AppConfig {
  return {
    ignored_names: [
      '.DS_Store',
      'Thumbs.db',
      'Gemfile.lock',
      'go.sum',
      'go.work.sum',
      'yarn.lock',
      'pnpm-lock.yaml',
      'composer.lock',
      'package-lock.json',
      'Cargo.lock',
    ],
    ignored_folders: [
      '.git',
      '.svn',
      '.hg',
      '.idea',
      '.vscode',
      '.vs',
      '.history',
      'node_modules',
      'bower_components',
      'jspm_packages',
      'web_modules',
      'dist',
      'build',
      'out',
      'target',
      'bin',
      'obj',
      'release',
      'debug',
      'pkg',
      '.next',
      '.nuxt',
      '.cache',
      '.parcel-cache',
      '.turbo',
      '.vercel',
      '.output',
      '__pycache__',
      '.pytest_cache',
      '.mypy_cache',
      '.tox',
      'venv',
      '.venv',
      'env',
      'bundler',
      'vendor',
      '.bundle',
      'checkouts',
      '.cargo',
      '.rustup',
      '.gradle',
      '.settings',
      '.classpath',
      '.project',
      'Properties',
      '_build',
      'deps',
      '_opam',
      'storage',
      'bootstrap/cache',
      'htmlcov',
      'coverage',
      '.nyc_output',
    ],
    binary_extensions: [
      'icns',
      'png',
      'jpg',
      'jpeg',
      'gif',
      'bmp',
      'ico',
      'svg',
      'webp',
      'tiff',
      'tif',
      'psd',
      'ai',
      'eps',
      'mp4',
      'avi',
      'mov',
      'wmv',
      'flv',
      'mkv',
      'webm',
      '3gp',
      'mp3',
      'wav',
      'flac',
      'aac',
      'ogg',
      'wma',
      'm4a',
      'zip',
      'rar',
      '7z',
      'tar',
      'gz',
      'bz2',
      'xz',
      'iso',
      'dmg',
      'pkg',
      'deb',
      'rpm',
      'exe',
      'dll',
      'so',
      'dylib',
      'bin',
      'msi',
      'msu',
      'ttf',
      'otf',
      'woff',
      'woff2',
      'eot',
      'pdf',
      'doc',
      'docx',
      'xls',
      'xlsx',
      'ppt',
      'pptx',
      'odt',
      'ods',
      'sqlite',
      'db',
      'db3',
      'mdb',
      'accdb',
      'pyc',
      'pyo',
      'pyd',
      'class',
      'jar',
      'war',
      'ear',
      'ds_store',
      'thumbs.db',
    ],
    token_limit: 128000,
    max_file_size: 1024 * 1024, // 1 MB
    output_template: '## {{path}}\n\n```{{language}}\n{{content}}\n```\n\n---\n\n',
  };
}

/**
 * Check if file is private (security check)
 */
export function isPrivateFile(name: string): boolean {
  const nameLower = name.toLowerCase();
  return (
    nameLower === '.env' ||
    nameLower.startsWith('.env.') ||
    nameLower.endsWith('.secret') ||
    nameLower.endsWith('.key') ||
    nameLower.endsWith('.pem') ||
    nameLower.includes('id_rsa') ||
    nameLower.includes('secrets')
  );
}
